remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Ensemble AI]
description: [A khub.ai article on Ensemble AI]
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

header_image: /assets/images/EnsembleAI.png